#!/bin/bash

# Creating the pathname(s).
export RESOURCES="/tmp/pathname/resources"
export CHECKER="/home/.checker"

# The username is required for this lab.
export USER=USERNAME_GOES_HERE

# Installing the required libraries.
apt-get update
apt-get install python pip python3-pip gcc -y
pip install flask

# Moving the checker scripts over.
mkdir $CHECKER
cp $RESOURCES/checker/* $CHECKER

# Create the responses directory.
mkdir /home/.checker/responses

# Moving into the /home/.checker directory.
pushd $CHECKER/

# Compiling the .c file.
gcc -o section_1 section_1.c

# Removing the .c file so that it's just binaries.
rm -f section_1.c

# Return to the /tmp directory.
popd

# Moving the save/load scripts.
cp $RESOURCES/*pathname.sh $CHECKER

# Change ownership of the checker directory.
chgrp -R $USER /home/.checker
chown -R $USER /home/.checker

# Make the responses directory writeable so that the wire_log.txt file can be made.
chmod o+w /home/.checker/responses

# Clean up.
rm -rf *
