#!/usr/bin/bash

if [ ! "$EUID" -ne 0 ]
  then echo "Please do not run ./port-forward-setup as root. Exiting."
  exit
fi

user=$(whoami)
current_xdc=$(hostname -f | cut -d- -f1)
# Replacing the . in the XDC with a dash for the config file:
xdc=${current_xdc//[.]/-}
tempfolder=port-forwarding-data
mkdir ~/$tempfolder

if [ -e $HOME/pass.txt ]; then
    pass=$(cat $HOME/pass.txt)
else
    pass=${PASSWORD}
fi

if [[ -z $pass ]]; then
    echo Password not set. Please create $HOME/pass.txt or set environment variable \$PASSWORD.
    exit 1
fi

mrg config set server grpc.mod.deterlab.net

echo "Logging $user into Merge"
mrg login $user -p $pass
if [[ $? -ne 0 ]]; then 
    echo Error logging in.
    exit 1
fi

echo "Successful sign-in. Key is up-to-date."
echo "Creating the files for port-forwarding $user onto a machine."

# Create a folder that will be used for zipping.
cd ~/$tempfolder

sudo cp ~/.ssh/merge_key ~/$tempfolder

touch config

# Creating the config file:
echo "Host mergejump
    Hostname jump.mod.deterlab.net
	Port 2022
	User $user
	IdentityFile ~/.ssh/merge_key
	ServerAliveInterval 30

Host $user-$xdc
    ProxyJump mergejump
    Hostname $xdc
    User $user
    IdentityFile ~/.ssh/merge_key
    ServerAliveInterval 30" >> config

# Clone the script files from GitHub:
echo "Installing/Updating Git..."
sudo apt-get -q update
sudo apt-get -q install git
git clone --quiet https://github.com/eric56379/deterlab-port-forwarding

# Downloading zip so that we can work with zip files instead of .tar.gz (caused issues before).
sudo apt-get -yq install zip

# Once completed, create the zip file. Remove it if it already exists.
cd ..
if [ -f ~/port-forward-data.zip ]; then
    rm -f ~/port-forward-data.zip
fi

cd ~/$tempfolder/
sudo chmod 766 deterlab-port-forwarding/port-forward-unix.sh
sudo zip -r ~/port-forward-data.zip deterlab-port-forwarding config merge_key --exclude \*.git\* --exclude \*.git\*/\*

# Clean up.
cd ~
rm -rf ~/port-forwarding-data/

RED='\033[0;31m' # Red Font
GREEN='\033[0;32m' # Green Font
NC='\033[0m' # No Color

printf "\n${GREEN}Completed.${NC} Check your home directory and download port-forward-data.zip. Extract it and access deterlab-port-forwarding/ for a README.md file for your next steps."
printf "\n${RED}IMPORTANT:${NC} Delete this .zip when you complete the setup. It contains your SSH key and should not be stored around freely!\n"
