#!/bin/bash

# Creating the pathname(s).
export RESOURCES="/tmp/buffer/resources"
export CHECKER="/home/.checker"

# The username is required for this lab.
export USER=niete018

# Installing the required libraries.
apt-get update
apt-get install build-essential cmake libncurses-dev pkg-config git -y

# Moving the checker scripts over.
mkdir $CHECKER
cp $RESOURCES/checker/* $CHECKER

# Create the responses directory.
mkdir /home/.checker/responses

# Moving the save/load scripts.
cp $RESOURCES/*buffer.sh $CHECKER

# Change ownership of the checker scripts.
chown -R $USER:$USER /home/.checker

# Make the responses directory writeable so that student responses can be made.
chmod o+w /home/.checker/responses

# Create the topic_1/ directory.
mkdir /home/$USER/topic_1
chown $USER:$USER /home/$USER/topic_1

# Update the username in the checker files. Used in the pathnames.
sed -i "s/USERNAME_FOR_NODE/$USER/g" /home/.checker/section_*.py

# Clean up.
rm -rf *