#!/bin/bash

# Creating the pathname(s).
export RESOURCES="/tmp/sqli/resources"
export CHECKER="/home/.checker"

# The username is required for this lab.
export USER=USERNAME_GOES_HERE

# Installing the required libraries.
apt-get update
apt-get install gcc python3-pip apache2 apache2-bin mariadb-server mariadb-client php7.4 libapache2-mod-php7.4 php7.4-cli php7.4-mysql libmariadb-dev -y

# Additionally, downloaded a couple pip libraries for the checker scripts.
python3 -m pip install --upgrade pip
pip install mysql-connector-python requests

# Moving the checker scripts over.
mkdir $CHECKER
chown $USER $CHECKER 
cp $RESOURCES/checker/* $CHECKER

# Moving the save/load scripts.
cp $RESOURCES/*sqli.sh $CHECKER

# Moving into the /home/.checker directory.
pushd $CHECKER/

# Compiling the .c files.
gcc -o check_sql check_sql.c

# Removing the .c files so that it's just binaries.
rm -f check_sql.c

# Return to the /tmp directory.
popd

# Now, go into the /tmp/sqli/resources/web_files directory.
cd $RESOURCES/web_files

### Installing FCCU.php.
cp index.html php_practice.php /var/www/html
cp FCCU.php /usr/lib/cgi-bin/

# Creating a copy of FCCU.php in the home directory.
cp FCCU.php /home/$USER

# Giving ownership to the student for php_practice.php and FCCU.php.
chown $USER /var/www/html/php_practice.php
chown $USER /usr/lib/cgi-bin/FCCU.php

# Create the responses directory.
mkdir /home/.checker/responses

# Giving ownership to the students so that the checker will work.
chown -R $USER $CHECKER

# Remove the password for root so that the checker will work.
mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '';"

# Creating the FCCU database.
mysql < fccu.sql

# Need to restart Apache, but first, turn errors on so that students will not get stuck.
sed -i 's/display_errors = Off/display_errors = On/' /etc/php/7.4/apache2/php.ini

# Required for getting the cgi-bin URL to work.
a2enmod cgi
systemctl restart apache2

# Make the responses directory writeable so that the wire_log.txt file can be made.
chmod o+w /home/.checker/responses

# Clean up.
rm -rf *
