#!/bin/bash

# Creating the pathname(s).
export RESOURCES="/tmp/posix/resources"
export CHECKER="/home/.checker"

# The username is required for this lab.
export USER=USERNAME_GOES_HERE

# Installing the required library.
apt-get update
apt-get install gcc -y

# Moving the checker scripts over.
mkdir $CHECKER
chown $USER $CHECKER 
cp $RESOURCES/checker/* $CHECKER

# Moving the save/load scripts.
cp $RESOURCES/*posix.sh $CHECKER

# Moving into the /home/.checker directory.
pushd $CHECKER/

# Compiling the .c files.
gcc -o run_me run_me.c

# Removing the .c files so that it's just binaries.
rm -f run_me.c

# Return to the /tmp directory.
popd

# Create empty text files for the posix lab.
mkdir /home/${USER}/posix_practice/
pushd /home/${USER}/posix_practice/
touch q1.txt q2.txt q3.txt
chmod 000 q*.txt
popd

# Create the special permissions directory.
mkdir /home/${USER}/special_permissions
pushd /home/${USER}/special_permissions
touch suid.sh sgid.sh
chmod 000 s*id.sh
mkdir sticky
chmod 000 sticky/
popd

# Create the responses directory.
sudo mkdir /home/.checker/responses

# Giving ownership to the students so that the checker will work.
chown -R $USER $CHECKER 

# Clean up.
# rm -rf *