#!/bin/bash

# Creating the pathname(s).
export RESOURCES="/tmp/server/resources"
export CHECKER="/home/.checker"

# The username is required for setting up this lab.
export USER=$(grep umdsec /etc/passwd | cut -d: -f1)

# Installing the required libraries.
apt-get update
apt-get install apache2 apache2-bin mariadb-server mariadb-client net-tools iptables -y

# Moving the checker scripts over.
mkdir $CHECKER
chown $USER $CHECKER 
cp $RESOURCES/checker/* $CHECKER

# Moving the save/load scripts.
cp $RESOURCES/*firewalls.sh $CHECKER

# Giving ownership to the students so that the checker will work.
chown -R $USER $CHECKER

# Make the responses directory writeable so that student's progress will save.
mkdir /home/.checker/responses
chmod o+w /home/.checker/responses

# Clean up.
# rm -rf *