#!/bin/bash

# Creating the pathname(s).
export RESOURCES="/tmp/intro/resources"
export CHECKER="/home/.checker"

# The username is required for this lab.
export USER=USERNAME_GOES_HERE

# Installing the required libraries.
apt-get update
apt-get install gcc screen inotify-tools -y

# Moving the checker scripts over.
mkdir $CHECKER
cp $RESOURCES/checker/* $CHECKER

# Moving the save/load scripts.
cp $RESOURCES/*intro.sh $CHECKER

# Moving into the /home/.checker directory.
pushd $CHECKER/

# Compiling the .c files.
gcc -o step4 step4.c
gcc -o step6 step6.c
gcc -o step9 step9.c

# Removing the .c files so that it's just binaries.
rm -f step*.c

# Return to the /tmp directory.
popd

# Change ownership of the checker directory so that the screen command works in run_inotify.sh.
chgrp -R $USER /home/.checker
chown -R $USER /home/.checker

# Begin a screen so that the home directory is tracked for steps 1-3.
sudo -u $USER /home/.checker/run_inotify.sh

# Create a hidden file for step 4.
echo "You found me!" > /usr/share/discover/dtd/.findme.txt
chown -R $USER /usr/share/discover/dtd/

# Clean up.
rm -rf *
